---
title: "Apache Arrow and the Sovereign Tech Fund"
subtitle: "A retrospective"
author:
  - Antoine Pitrou
  - Raúl Cumplido
date: 14 10 2026
date-format: long
format:
  revealjs:
    slide-number: true
    incremental: false
---

# Introduction

## Outline

- Motivation
- The application process
- The funded work
- Retrospective
- Funding and ASF governance
- Takeaways for other projects
- Q&A (10-15 min)

## About us

- Antoine Pitrou
  - Contributor to Apache Arrow since 2018
  - Apache Arrow PMC member, Parquet PMC member and ASF member
  - CPython core developer
  - Technical director at [QuantStack](https://quantstack.net/)
- Raúl Cumplido
  - Contributor to Apache Arrow since 2022
  - Apache Arrow PMC member and ASF member
  - Scientific Software Engineer at [QuantStack](https://quantstack.net/)

## What is Apache Arrow?

It provides fundamental open building blocks for data science, analytics and scientific computing.

 - Universal columnar in-memory format
 - Multi-language toolbox for in-memory analytics and fast data interchange

Two pillars:

 - A set of community-approved specifications for platform-agnostic data sharing
 - A set of reference implementations of these specifications

## Project history: early days (1)

- Arrow was founded in 2016
- At project start, two major implementations: Java and C++
- Arrow C++ the basis for Python, R, Ruby implementations
- All implementations in a monorepo
- Arrow C++ quickly became dominant

## Project history: VC-backed development (2)

- From 2018 to 2024, significant financial investment in Arrow C++ (Ursa Labs, then Voltron Data)
- Many components added to the codebase (filesystems, compute layer, etc.)
- Many optional dependencies
- Up to ~600k lines of C++ code
- Massive amount of CI jobs
  (typical nightly builds in 2024: 87 test builds, 72 packaging builds,
  51 release verification builds)

## Project history: other implementations (3)

- Other implementations were founded and took off (Go, Rust), with
  development and maintenance ensured by other subsets of the community
- They were progressively moved to separate repositories

## Motivation for seeking funding

- Voltron Data, a VC-backed company, ceased almost all investment in 2024
- Funding had been feature-driven, with less regard for maintenance concerns
  * Keeping codebase lean and manageable was never a factor
- The ex-monorepo (C++, Python, R, Ruby) faced a maintenance cliff
  * Other implementations less affected
- An immediate need to keep the lights on (CI maintenance, release management...)

## What is the Sovereign Tech Fund?

- [Sovereign Tech Agency](https://www.sovereign.tech/) is a German agency funded
  by the German government
- STF: "invest globally in the open software components that underpin Germany's
  and Europe's competitiveness and ability to innovate"
- Dozens of open source projects funded: list at <https://www.sovereign.tech/tech>
- Typical funding is 100-500 k€ per project
- The STA has other funding programs (Fellowship, Resilience...)

## STF requirements

- Project must be open source
- Project should have a significant impact in the broader society
- Proposed work should focus on software development and maintenance
- Proposed work should contribute to project sustainability, reliability,
  maintenance, security
- Applicants should be experts on the project

# The application

## Summary

- Initial submission in March 2025
- Backed by our employer QuantStack
- Proposed work spans two years (up to half 2027)
- Finally approved end of July 2025; work started September 2025

## About STF's proposals structure

Standard structure Web form submission followed by a detailed Notion page.

The 6 question topics we were asked:

- Technology description
- Relevance & public interest
- Problems & proposed work
- Team and why it qualifies
- Governance & community approval
- Work Packages

## Identifying what needed investment (1)

Previous work on the project helped us understand the pain points

- **Maintenance challenges**:
  - 200+ CI jobs distributed over multiple CI providers
  - Keeping the lights on was an immediate problem
  - Release Process steps were manual, overall complex process and time consuming

## Identifying what needed investment (2)

- **Security concerns**:
  - Lack of automation to find potential vulnerabilities
  - Lack of modern software supply chain practices (SBOMs)
- **Sustainability issues**:
  - Build systems were obsolete (Legacy CMake and setuptools build systems)
  - Lack of modularity in the codebase

## Our proposal structure

- 11 work packages
  * 8 bounded initiatives
  * 3 "keep the lights on" packages (release management, CI maintenance, community management)

- Each work package has a well-defined scope and budget

- 338 days of work spanning 2 calendar years, with a fixed daily rate

- Indicative schedule provided

# The work

## Timeline


## Release management

- Improvements to Release Process: 20 days
  - Work on reproducible builds to automate signing
  - Reproducible Linux binaries (Debian)
  - Clarify release documentation and improve automated scripts
  - Enable immutable releases on GitHub
- Deliver Arrow Releases during 2 years: 34 days
  - Deliver Arrow Releases according to the planned quarterly schedule
    - 22.0.0 (Oct 2025), 23.0.0 (Jan 2026), 24.0.0 (Apr 2026), 25.0.0 (Jul 2026), 26.0.0 (Oct 2026)
  - Deliver patch releases when necessary
    - 23.0.1 (Feb 2026), 25.0.1 (Aug 2026)

::: {.notes}
Both improve release process and deliver releases.
:::

## CI infrastructure

- Improvements to Arrow’s continuous integration: 20 days
- Operational maintenance of Arrow’s continuous integration (CI) infrastructure for 2 years: 34 days

TODO

::: {.notes}
Improve CI + CI maintenance
:::

## Security

- Fuzz testing: 30 days of work
  - Improve existing fuzzers
  - Add new fuzzers
  - Fix issues found by fuzzing improvements
  - Outcome: dozens of issues fixed, mainly in Parquet reader

TODO

::: {.notes}
Fuzz testing + Supply Chain Security
:::

## Build improvements

TODO

::: {.notes}
Improve C++ and Python build systems.
Improve modularity of the arrow libraries.
:::

## Maintenance and Community Management

## Milestones and reporting

- We chose time-based reporting

- Reporting and invoicing done on a monthly basis: timesheet (time per WP) + detailed list of issues/PRs

TODO

::: {.notes}
Initial milestones planned and how reporting works
Real milestones.
:::

# Retrospective

## What went well

- Process was smooth, though the initial decision took longer than expected
- Reporting is quite straightforward
- Lots of delivered improvements to the Apache Arrow project maintenance and overall quality

::: {.notes}
:::

## Mistakes and shortcomings

- Over-specified work package: "Improve fuzzing" should have been a more
  general package of improving software security.

TODO

::: {.notes}
Maintenance is ongoing and requires continuous attention which is still underfunded.
Lots of things have changed since 1.5 years ago (AI rise) with both the landscape of funding
and the priorities within the Apache Arrow project.
:::

## What's still left

TODO

::: {.notes}
Ongoing maintenance tasks.
Future improvements planned.
:::

# Funding and ASF governance

## Paid work in a volunteer-driven project

- "Volunteer" often means professionally involved, but without any official
  recognition from employer.
  * Especially true for Arrow which is 1) technically complex
    2) at the basis of many data science / analytics stacks

- Often, a "volunteer" can only contribute as long as their employer tacitly agrees
  (and their day work leaves enough time for it)
  * => intrinsically fragile, and emotionally awkward

- Most employers have little concern for maintenance and sustainability of projects
  not under their control

- STF fosters a more honest and healthier situation ("S pays me for maintenance")

::: {.notes}
How can we fund ongoing maintenance and quality improvements in a volunteer-driven project?

XXX Not sure what to say about ASF governance
:::

# Takeaways for other projects

TODO

::: {.notes}
???
:::

## Q&A
